version: '2'
services:
    web:
        build: web
        ports:
            - "80:80"
            - "40000-40100:40000-40100"
        volumes:
            - /developpement/docker/docker_sf2_env/config/php.ini:/usr/local/etc/php/php.ini
            - /developpement/docker/docker_sf2_env/config/vhost/:/etc/apache2/sites-enabled/
            - /developpement/sfProjects/sf2/:/var/www/html/
        links:
            - db
        environment:
            - ALLOW_OVERRIDE=All
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /developpement/docker/mysql:/var/lib/mysql